# Generated by Django 3.2 on 2021-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApp', '0002_account_avatar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на аватар'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='аватарка пользователя'),
        ),
    ]
