# Generated by Django 3.2 on 2021-05-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApp', '0003_auto_20210511_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar_link',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='широта'),
        ),
    ]
