# Generated by Django 3.2 on 2021-05-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaceRememberApp', '0005_auto_20210514_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
    ]
